---
title: "ARCH"
title-block-banner: banner2.png
---

Copied from [https://www.alzheimers.gov/taking-action/national-research-centers](https://www.alzheimers.gov/taking-action/national-research-centers): 

Originally established in 1984, the Alzheimer’s Disease Research Centers (ADRCs) are Congressionally designated Centers of Excellence. The ADRCs support the nation’s increased effort to address Alzheimer’s disease (AD) and Alzheimer’s disease-related dementias (ADRD) by providing information, local resources, support, and opportunities to participate in research. These centers are dedicated to developing and testing new ways to detect, diagnose, treat, and prevent dementia and to improving care for people with these diseases and their families. NIA and NIH fund ADRCs at research institutions across the United States. Each Center has a specific theme based on local populations and scientific areas of interest.

The ADRC program prioritizes collaboration and communication, as well as sharing resources, approaches, and results among centers and to outside researchers. By working collaboratively, the ADRCs have made significant contributions to addressing AD and ADRD.

For families affected by Alzheimer’s and related dementias, ADRCs offer:

Help with obtaining diagnosis and managing care for persons living with dementia
Information about the diseases, new research findings, services, and resources
Opportunities to learn about active clinical trials and participate in research studies that contribute to improved understanding of dementia, which may lead to new treatments and better care
Support groups and other special programs for volunteers and their families
Opportunity to obtain an autopsy at end of life, with a report provided to the family
The History of Alzheimer’s Disease Research Centers
The main objectives of the ADRCs program are to:

Conduct cutting-edge basic, clinical, and translational research and provide resources and infrastructure to address AD and ADRD Research Implementation Milestones
Train the next generation of researchers in an environment that supports interactions across scientific disciplines
Provide information to the public about research findings, access to support services, and opportunities to participate in research
How Alzheimer’s Disease Research Centers Advance Research
ADRCs conduct research spanning from the causes of and risk factors for AD and ADRD to potential treatments to managing symptoms and helping families cope. Center activities include: 

Clinical Research: ADRCs each have a “Clinical Core” of research volunteers who come to the ADRC annually as part of a long-term study of aging and the brain. Volunteers complete annual tests and assessments that help researchers gather invaluable data to explore innovative approaches to diagnosis, treatment, and disease prevention.
Outreach, Recruitment and Engagement: Each of the centers supports robust efforts to help raise awareness of AD and ADRD, inform the public about the latest research, support families, and recruit people to participate in research. ADRCs have created community programs, support groups, and informational materials. Centers recruit volunteers from their local community with a focus on populations that are understudied and/or are at higher risk for AD/ADRD to participate in research. To facilitate knowledge sharing across centers and with the wider dementia research community, many resources are available through the NIA-supported Alzheimer’s and Dementia Outreach, Recruitment, and Engagement (ADORE) repository.
Data Sharing: Data collection and sharing helps researchers better understand diseases and develop effective treatment and prevention strategies. ADRCs share data and samples with a number of connected AD and ADRD repositories. The National Alzheimer’s Coordinating Center collects standardized data from all of the ADRCs and shares deidentified data with other qualified investigators. The ADRCs also send biological samples to the National Centralized Repository for Alzheimer’s Disease and Related Dementias, genetic information to the Alzheimer's Disease Genetics Consortium, and brain scans to the Standardized Centralized Alzheimer’s and Related Dementias Neuroimaging. These large-scale data sharing efforts enable researchers to make discoveries that would not be possible with smaller sample sizes.
Much of the important progress in Alzheimer’s and other dementia research in the United States during the past 40 years stems from research conducted at — or with the help of resources provided by — the ADRCs. For example, ADRC researchers have:

Conducted a significant amount of the research on the processes behind amyloid plaque and tau tangle formation in the brain, which are hallmarks of Alzheimer's disease.
Characterized abnormal proteins associated with several different neurodegenerative diseases.
Evaluated cognitive changes associated with normal aging and the transitions from early difficulties thinking and remembering to dementia.
Identified factors that contribute to changes in cognitive abilities, such as social and physical activity.
Related changes in brain structure to the clinical stages of Alzheimer's using information gathered from participants during cognitive tests and assessments, brain imaging scans, and autopsies of donated brains.
Helped to define a newly described type of dementia, Limbic-Predominant Age-Related TDP-43 Encephalopathy (LATE)

---

### Data Dictionary, Metadata, Years Available { .unnumbered}

- **Years Available**:
- **Geography**:
- **Population**:
- **Documentation**:
- Tutorial from BU Libraries:

### How to access

Reach out to [bedacprp@bu.edu](mailto:bedacprp@bu.edu) to request a dataset designated by:
-

### Related Publications

-


### Getting started

- [Download Getting Started Guide]()
