---
title: "DataAxle"
title-block-banner: banner2.png
---

Data Axle provides comprehensive business and consumer data that includes millions of U.S. business records, categorized by industry using enhanced NAICS and SIC codes. These data enable granular analysis of resource access and utilization at geographic resolutions as small as the Census Block. Data are updated annually and include information about site, employee size and revenue.

---

### Data Dictionary, Metadata, Years Available { .unnumbered}

- **Years Available**: 1997-2024 
- **Geography**: Geocoded point-of-interest data
- **Population**: United States
- **Documentation**:
  - Tutorial from BU Libraries: https://library.bu.edu/dataaxle

### How to access

Reach out to [bedacprp@bu.edu](mailto:bedacprp@bu.edu) to request a dataset designated by:
- Year
- Business code (NAICS, SIC)
- Zip code (optional)
- State (optional)
- Location or parent employee size (optional)
- Location or parent sales volume code (optional)
- Gender of contact or executive (optional)

### Related Publications

- Nori-Sarma A, Spangler KR, Wang B, Cesare N, Dukes KA, Lane KJ. Impacts of the choice of distance measurement method on estimates of access to point-based resources. J Expo Sci Environ Epidemiol. 2023 Mar;33(2):237-243. doi: 10.1038/s41370-022-00414-z. Epub 2022 Feb 10. PMID: 35145207.


### Getting started

- [Download Getting Started Guide (.pptx)](docs/DataAxle_intro_and_extraction_share.pptx)
