---
title: "Welcome"
title-block-banner: banner2.png
layout: "columns"
---

The Center for Health Data Sciences **Data Hub** is a university-wide consultation service designed to help faculty and staff navigate the fast-moving world of **data science, machine learning, and AI**. Whether you're just getting started or exploring advanced analytic strategies, the Data Hub is your **first stop for expert advice**.

---
:::: {.columns}

::: {.column width="47%"}
###  What We Offer {  .unnumbered} 

Our team of data specialists provides short, targeted consultations to help researchers:

- Discover and evaluate relevant [**data sources**](data_sources.qmd).
- Learn about [**research environments**](data_infrastructure.qmd) available at BU
- Provide feedback on **research design** 
- Facilitate **collaboration** across BU

These 30-minute sessions are offered at no cost and are open to faculty and staff across BU.
:::

::: {.column width="6%"}
:::

::: {.column width="47%"}
### How It Works

1. **Submit a Request**: Email us at <a href="mailto:bedacprp@bu.edu" class="btn btn-primary" role="button" style="border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); transition: box-shadow 0.3s ease;"
   onmouseover="this.style.boxShadow='0 6px 12px rgba(0, 0, 0, 0.2)'"
   onmouseout="this.style.boxShadow='0 4px 6px rgba(0, 0, 0, 0.1)'">BEDAC Proposals</a>
2. **We’ll Schedule a Session**: A data expert will meet with you virtually or in person
3. **Get Connected**: If your request needs more follow-up, we’ll refer you to the right partner in CHDS, BEDAC, or beyond

We use a centralized request system to track usage trends and continuously improve service.
:::
::::


:::: {.columns}

::: {.column width="47%"}
### Topics We Cover

Our team can help with questions related to:

- Sourcing internal and external datasets
- Data licensing and permissions
- IRB and data use agreements (DUAs)
- Matching your research question to the right method or tool
- Building collaborations across BU
:::

::: {.column width="6%"}
:::

::: {.column width="47%"}


### Strategic Benefits

The Data Hub isn’t just about problem-solving—it’s about enabling research at BU to reach its full potential. The Hub helps:

- **Break down silos** across schools and research centers
- **Strengthen proposals** by improving data and methodology plans
- **Save time**, letting investigators focus on analysis instead of logistics
:::
::::

> _The BU Data Hub is powered by CHDS and BEDAC at the BU School of Public Health, with support from research and IT partners across the university._

