---
title: "ADVANCE / OCHIN"
title-block-banner: banner2.png
---

From [advancecollaborative.org/data-warehouse](https://advancecollaborative.org/data-warehouse/):

The ADVANCE Data Warehouse (DW) is the nation’s largest and most comprehensive database on community-based health care and outcomes, representing over 14 million patients nationwide. As the single largest source of primary care data within PCORnet®, ADVANCE combines electronic health records (EHR) using the PCORnet® Common Data Model, a standardized, research-ready format designed for scalable, multi-site studies. This shared Common Data Model makes varied types of data, including demographics, vital signs, labs, clinical observations, diagnoses, and more, available for research across a diverse and expansive set of participating sites.

Data offerings include:

ADVANCE Research Overview is a high-level summary of the ADVANCE Clinical Research Network (CRN), ideal for investigators interested in project collaboration.

ADVANCE and OCHIN Data Dictionary and User Guide provides in-depth details on the data domains, tables, and variables available for research within the ADVANCE CRN.

### Publications

Boone-Heinonen, Janne, Carrie J. Tillotson, Jean P. O'Malley, Miguel Marino, Sarah B. Andrea, Andrew Brickman, Jennifer DeVoe, and Jon Puro. "Not so implausible: impact of longitudinal assessment of implausible anthropometric measures on obesity prevalence and weight change in children and adolescents." Annals of epidemiology 31 (2019): 69-74.
[link](https://doi.org/10.1016/j.annepidem.2019.01.006)

### How to access

Reach out to [bedacprp@bu.edu](mailto:bedacprp@bu.edu)

